export { AuthModule } from './auth/auth.module';
export { PatientsModule } from './patients/patients.module';
export { NutritionistModule } from './nutritionist/nutritionist.module';
export { DietsModule } from './diets/diets.module';
export { SubstitutionListModule } from './substitution-list/substitution-list.module';
export { MedicalPrescriptionModule } from './medical-prescription/medical-prescription.module';
export { TaskModule } from './task/task.module';
export { AnthropometryModule } from './anthropometry/anthropometry.module';
export { AgendaModule } from './agenda/agenda.module';
