import { COLORS } from '@constants'

export const DAILY_TASK_STATUS = {
  DONE: 'DONE',
  NOT_DONE: 'NOT_DONE',
}

export const DAILY_TASK_NEXT_STATUS = {
  [DAILY_TASK_STATUS.DONE]: DAILY_TASK_STATUS.NOT_DONE,
  [DAILY_TASK_STATUS.NOT_DONE]: null,
}

export const DAILY_TASK_STATUS_ICON = {
  [DAILY_TASK_STATUS.DONE]: 'check-bold',
  [DAILY_TASK_STATUS.NOT_DONE]: 'close-thick',
}

export const DAILY_TASK_STATUS_ICON_COLOR = {
  [DAILY_TASK_STATUS.DONE]: COLORS.SUCCESS_GREEN,
  [DAILY_TASK_STATUS.NOT_DONE]: COLORS.ERROR_RED,
}
